// GENERATED by scripts/extract-parts.mjs — do not edit by hand.
// Model facts only. label (presentation) and tool (per action) live elsewhere.
import { PartDef } from "@/game/core/type";

export const PARTS = {
  "tableTop": {"partId":"tableTop","group":"tableTop","meshName":"whole_tableTop","type":"structural","cluster":"whole","pose":{"position":[0,0.4245,0],"rotation":[0.5,0.5,-0.5,0.5]}},
  "screw115980_4": {"partId":"screw115980_4","group":"screw115980","meshName":"whole_screw115980_4","type":"fastener","cluster":"whole","engageDir":[0,1,0],"pose":{"position":[-0.2485,0.4005,-0.2485],"rotation":[-0.49107,-0.508774,-0.508773,0.491069]}},
  "screw115980_2": {"partId":"screw115980_2","group":"screw115980","meshName":"whole_screw115980_2","type":"fastener","cluster":"whole","engageDir":[0,1,0],"pose":{"position":[0.2485,0.4005,0.2485],"rotation":[-0.433011,-0.559019,-0.559018,0.43301]}},
  "screw115980_1": {"partId":"screw115980_1","group":"screw115980","meshName":"whole_screw115980_1","type":"fastener","cluster":"whole","engageDir":[0,1,0],"pose":{"position":[0.2485,0.4005,-0.2485],"rotation":[-0.378155,-0.597495,-0.597494,0.378154]}},
  "leg_1": {"partId":"leg_1","group":"leg","meshName":"whole_leg_1_screw115980_1","type":"structural","cluster":"whole","attach":"screw115980_1","pose":{"position":[0.2485,0,-0.2485],"rotation":[-0.5,0.5,0.5,0.5]}},
  "leg_4": {"partId":"leg_4","group":"leg","meshName":"whole_leg_4_screw115980_4","type":"structural","cluster":"whole","attach":"screw115980_4","pose":{"position":[-0.2485,0,-0.2485],"rotation":[0,0.707107,0.707107,0]}},
  "leg_3": {"partId":"leg_3","group":"leg","meshName":"whole_leg_3_screw115980_3","type":"structural","cluster":"whole","attach":"screw115980_3","pose":{"position":[-0.2485,0,0.2485],"rotation":[0,0.707107,0.707107,0]}},
  "leg_2": {"partId":"leg_2","group":"leg","meshName":"whole_leg_2_screw115980_2","type":"structural","cluster":"whole","attach":"screw115980_2","pose":{"position":[0.2485,0,0.2485],"rotation":[0,0.707107,0.707107,0]}},
  "screw115980_3": {"partId":"screw115980_3","group":"screw115980","meshName":"whole_screw115980_3","type":"fastener","cluster":"whole","engageDir":[0,1,0],"pose":{"position":[-0.2485,0.4005,0.2485],"rotation":[-0.547693,-0.44725,-0.44725,0.547692]}},
} satisfies Record<string, Omit<PartDef, "label" | "tool">>;

export type PartId = keyof typeof PARTS;
export const ALL_PART_IDS = Object.keys(PARTS) as PartId[];
